os: linux
language: python
python:
  - 3.5

addons:
  apt:
    packages:
      - python-gi
      - python3-gi
      - python-dbus
      - python3-dbus

before_install:
  - rm ~/virtualenv/python3.5/no-global-site-packages.txt # Hack

install:
  - pip install -r "pip_reqs.txt"

script:
  - python -m pytest tests/test_libnotify.py

after_success:
  - coverage run src/libnotify_terminal.py
  - coverage xml
  - python-codacy-coverage