version: 2
jobs:
    deps:
        docker:
            -
                image: 'circleci/python:3.5.3'
        steps:
            - checkout
            -
                restore_cache:
                    keys:
                        - 'v1-deps-{{ checksum "pip_reqs.txt" }}'
            -
                run:
                    name: Install dependencies
                    command: |
                        python3 -m venv venv --system-site-packages
                        . venv/bin/activate
                        pip install -r pip_reqs.txt
            -
                save_cache:
                    key: 'v1-deps-{{ checksum "pip_reqs.txt" }}'
                    paths:
                        - ./venv
    build:
        docker:
            -
                image: 'circleci/python:3.5.3'
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-deps-{{ checksum "pip_reqs.txt" }}
            - run:
                name: Install system dependencies
                command: sudo apt-get install python-notify2 python3-notify2
            - run:
                    name: Compile
                    command: |
                        ls -al
                        . venv/bin/activate
                        make
    test:
        docker:
            -
                image: 'circleci/python:3.5.3'
        steps:
            - checkout
            -
                restore_cache:
                    keys:
                        - 'v1-deps-{{ checksum "pip_reqs.txt" }}'
            -
                run:
                    name: Install system dependencies
                    command: sudo apt-get install python-nofity2 python3-notify2
            -
                run:
                    name: Run tests
                    command: |
                        ls -al
                        . venv/bin/activate
                        make test
            -
                run:
                    name: Generate Codacy Coverage
                    command: |
                        . venv/bin/activate
                        make coverage
            -
                store_artifacts:
                    path: coverage.xml
                    prefix: codacy-coverage
workflows:
    version: 2
    test:
        jobs:
            - deps
            -
                test:
                    requires:
                        - deps
